jobs:
  - job: Properties
    pool:
      # vmImage: ubuntu-latest
      name: "SDP-CICD-self-hosted-agents-pool"
      demands: ProxyConexus -equals True
    steps:
      - script: |
          echo %%BuildNumber%% $(Build.BuildNumber)
          echo %%BuildId%% $(Build.BuildId)
          echo %%DefinitionName%% $(Build.DefinitionName)
          echo %%QueuedById%% $(Build.QueuedById)
          echo %%JobId%% $(System.JobId)
          echo %%TeamProjectId%% $(System.TeamProjectId)
          curl -L -X GET -x http://proxy.conexus.svc.local:3128 https://iltlvd-scrum-211-34.intl.att.com:9443/ -H 'Content-Type: application/json'

# curl -L -X POST -x http://proxy.conexus.svc.local:3128 https://iltlvd-scrum-211-34.intl.att.com:9443/ -H 'Content-Type: application/json' --data-raw '{}'

  # - job: RestCall
  #   pool: server
  #   steps:
  #     - task: InvokeRESTAPI@1
  #       inputs:
  #         connectionType: ConnectedServiceName
  #         serviceConnection: iltlvd-scrum-211-34
  #         method: POST
  #         headers: >-
  #           {Content-Type:application/json, PlanUrl: $(system.CollectionUri),
  #           ProjectId: $(system.TeamProjectId), HubName: $(system.HostType),
  #           PlanId: $(system.PlanId), JobId: $(system.JobId), TimelineId:
  #           $(system.TimelineId), TaskInstanceId: $(system.TaskInstanceId),
  #           AuthToken: $(system.AccessToken)}
  #         body: '{}'

